Quizzes 7 and 8

In [5]:
import numpy as np
import pandas as pd

In [22]:
data = np.random.rand(100,5)

In [11]:
data.shape

(100, 5)

In [23]:
data[:, 2]

array([0.23234711, 0.89083906, 0.60863868, 0.03598053, 0.76388692,
       0.16293106, 0.34588873, 0.70304425, 0.04769386, 0.22251762,
       0.90244237, 0.28933841, 0.59991621, 0.99947183, 0.84188651,
       0.32494865, 0.49550038, 0.52917504, 0.18292641, 0.64049345,
       0.27204755, 0.81967691, 0.28326688, 0.67163979, 0.81737373,
       0.30217736, 0.63818318, 0.48112932, 0.85262547, 0.03490712,
       0.92860177, 0.14482943, 0.05526273, 0.33464823, 0.17393589,
       0.02777968, 0.96102488, 0.50985708, 0.83765803, 0.74150867,
       0.57850407, 0.24231712, 0.41029481, 0.57721479, 0.18760181,
       0.78247191, 0.796206  , 0.65448972, 0.21853581, 0.77379462,
       0.14318579, 0.20299839, 0.17885032, 0.46968891, 0.19622476,
       0.55869413, 0.4300087 , 0.4076104 , 0.6717991 , 0.88083186,
       0.23630831, 0.84452263, 0.07020073, 0.90064219, 0.79626728,
       0.6311429 , 0.84712851, 0.21241695, 0.42043759, 0.8697511 ,
       0.59098351, 0.11185769, 0.00169221, 0.41285713, 0.53647

In [24]:
data[:, 2].shape

(100,)

In [26]:
data[:, :3].shape

(100, 3)

In [27]:
data[:10, 3:]

array([[0.22963123, 0.8534411 ],
       [0.44479167, 0.70294981],
       [0.98847826, 0.84555037],
       [0.54335598, 0.72614315],
       [0.86738087, 0.69312081],
       [0.09473848, 0.28522122],
       [0.30268485, 0.22381128],
       [0.52825242, 0.36610919],
       [0.68762786, 0.51406032],
       [0.20726501, 0.54391979]])

In [17]:
data[:10, 3:].shape

(10, 2)

In [28]:
grid = [['tea', 'coffee'], ['water', 'juice'], ['soda', 'milk']]

In [20]:
grid[2][0]

'soda'

In [21]:
count = 0
tools = ['hammer', 'saw']
for item in tools:
    count += 1
print('There are', count, 'tools in the list.')


There are 2 tools in the list.


In [30]:


# --- Make a toy dataframe ---
data = {
    'year1': [50, 120, 95, 130, 10, 2],
    'year2': [60, 80, 110, 140, 20, 2],
    'year3': [70, 90, 105, 150, 30, 2],
    'year4': [80, 100, 115, 160, 40, 2],
    'year5': [90, 110, 125, 170, 50, 2]
}

df = pd.DataFrame(data)

print("Full df:")
print(df)


Full df:
   year1  year2  year3  year4  year5
0     50     60     70     80     90
1    120     80     90    100    110
2     95    110    105    115    125
3    130    140    150    160    170
4     10     20     30     40     50
5      2      2      2      2      2


In [31]:
df.head()

,year1,year2,year3,year4,year5
0,50,60,70,80,90
1,120,80,90,100,110
2,95,110,105,115,125
3,130,140,150,160,170
4,10,20,30,40,50


In [2]:
# Option 1: bracket notation (most common)
year3_col = df['year3']

# Option 2: using .loc with all rows, 'year3' column
year3_col_loc = df.loc[:, 'year3']

print("\nYear 3 column (by label):")
print(year3_col)



Year 3 column (by label):
0     70
1     90
2    105
3    150
4     30
Name: year3, dtype: int64


In [32]:
filtered = df[df['year1'] >= 100]

print("\nRows where year1 >= 100:")
print(filtered)


Rows where year1 >= 100:
   year1  year2  year3  year4  year5
1    120     80     90    100    110
3    130    140    150    160    170


In [33]:
df['year1'] >= 100

0    False
1     True
2    False
3     True
4    False
5    False
Name: year1, dtype: bool

In [34]:
.1 + .2

0.30000000000000004

In [35]:
 X = np.array([[0,3,0], [2,0,0]])

In [36]:
for x in X:
    print(x)

[0 3 0]
[2 0 0]


In [37]:
testx = ([[0,0,0]])

In [39]:
dst = np.array([round(np.linalg.norm(X[x]-testx), ndigits = 2) for x in X])

IndexError: index 3 is out of bounds for axis 0 with size 2

In [40]:
np.linalg.norm(X[0]-testx)

3.0